import type { Bet } from './types';
import { sub } from 'date-fns';

export const INITIAL_BETS: (Omit<Bet, 'date'> & { date: Date | string })[] = [
  {
    id: '1',
    type: 'single',
    sport: 'Football',
    event: 'Real Madrid vs Barcelona',
    betType: 'Match Winner',
    stake: 50,
    odds: 2.5,
    status: 'won',
    date: sub(new Date(), { days: 15 }),
    notes: 'Aposta de valor baseada no histórico recente.',
  },
  {
    id: '2',
    type: 'single',
    sport: 'Basketball',
    event: 'Lakers vs Celtics',
    betType: 'Total Points',
    stake: 100,
    odds: 1.9,
    status: 'lost',
    date: sub(new Date(), { days: 14 }),
    earnedFreebetValue: 10,
  },
  {
    id: '3',
    type: 'surebet',
    sport: 'Tennis',
    event: 'Alcaraz vs Sinner',
    status: 'won',
    date: sub(new Date(), { days: 12 }),
    subBets: [
        { id: '3a', bookmaker: 'Betano', betType: 'Alcaraz to win', odds: 1.8, stake: 56.90, isFreebet: false },
        { id: '3b', bookmaker: 'Pinnacle', betType: 'Sinner to win', odds: 2.4, stake: 43.10, isFreebet: false },
    ],
    totalStake: 100,
    guaranteedProfit: 2.42,
    profitPercentage: 2.42,
    notes: 'Surebet encontrada 5 minutos antes do jogo.',
  },
  {
    id: '4',
    type: 'single',
    sport: 'Football',
    event: 'Man City vs Arsenal',
    betType: 'Both Teams to Score',
    stake: 75,
    odds: 1.75,
    status: 'lost',
    date: sub(new Date(), { days: 10 }),
  },
  {
    id: '5',
    type: 'single',
    sport: 'Baseball',
    event: 'Yankees vs Red Sox',
    betType: 'Money Line',
    stake: 60,
    odds: 2.1,
    status: 'pending',
    date: new Date(),
  },
  {
    id: '6',
    type: 'single',
    sport: 'Football',
    event: 'Liverpool vs Chelsea',
    betType: 'Over/Under 2.5 Goals',
    stake: 100,
    odds: 1.80,
    status: 'won',
    date: sub(new Date(), { days: 5 }),
    notes: 'Ótima odd para um jogo com tendência de gols.',
  },
  {
    id: '7',
    type: 'single',
    sport: 'Basketball',
    event: 'Warriors vs Nuggets',
    betType: 'Point Spread',
    stake: 50,
    odds: 1.91,
    status: 'pending',
    date: sub(new Date(), { hours: -2 }),
  },
  {
    id: '8',
    type: 'surebet',
    sport: 'Futebol',
    event: 'MIRASSOL X BOTAFOGO',
    status: 'won',
    date: sub(new Date(), { days: 1 }),
    subBets: [
        { id: '8a', bookmaker: 'BET365', betType: 'EMPATE', odds: 3.40, stake: 50.00, isFreebet: false },
        { id: '8b', bookmaker: 'SUPERBET', betType: '+2.5', odds: 45.00, stake: 3.60, isFreebet: false },
        { id: '8c', bookmaker: 'BETBRA', betType: 'CASA OU FORA', odds: 1.38, stake: 116.00, isFreebet: false },
    ],
    totalStake: 169.60,
    guaranteedProfit: 0,
    profitPercentage: 0,
    earnedFreebetValue: 50,
    notes: 'Surebet para ganhar freebet de R$ 50.',
  }
];


export const SPORTS: string[] = ['Football', 'Basketball', 'Tennis', 'Baseball', 'Other'];
