import type { Bet } from './types';

export const INITIAL_BETS: Bet[] = [
  {
    id: '1',
    sport: 'Football',
    match: 'Real Madrid vs Barcelona',
    market: 'Match Winner',
    selection: 'Real Madrid',
    stake: 50,
    odds: 2.5,
    result: 'won',
    date: new Date('2024-05-01T19:00:00.000Z').toISOString(),
  },
  {
    id: '2',
    sport: 'Basketball',
    match: 'Lakers vs Celtics',
    market: 'Total Points',
    selection: 'Over 220.5',
    stake: 100,
    odds: 1.9,
    result: 'lost',
    date: new Date('2024-05-02T23:30:00.000Z').toISOString(),
  },
  {
    id: '3',
    sport: 'Tennis',
    match: 'Alcaraz vs Sinner',
    market: 'Set Betting',
    selection: 'Alcaraz 2-1',
    stake: 25,
    odds: 4.0,
    result: 'won',
    date: new Date('2024-05-03T14:00:00.000Z').toISOString(),
  },
  {
    id: '4',
    sport: 'Football',
    match: 'Man City vs Arsenal',
    market: 'Both Teams to Score',
    selection: 'Yes',
    stake: 75,
    odds: 1.75,
    result: 'lost',
    date: new Date('2024-05-04T16:30:00.000Z').toISOString(),
  },
  {
    id: '5',
    sport: 'Baseball',
    match: 'Yankees vs Red Sox',
    market: 'Money Line',
    selection: 'Yankees',
    stake: 60,
    odds: 2.1,
    result: 'pending',
    date: new Date().toISOString(),
  },
  {
    id: '6',
    sport: 'Football',
    match: 'Liverpool vs Chelsea',
    market: 'Over/Under 2.5 Goals',
    selection: 'Over 2.5',
    stake: 100,
    odds: 1.80,
    result: 'won',
    date: new Date('2024-05-10T15:00:00.000Z').toISOString(),
  },
  {
    id: '7',
    sport: 'Basketball',
    match: 'Warriors vs Nuggets',
    market: 'Point Spread',
    selection: 'Warriors +5.5',
    stake: 50,
    odds: 1.91,
    result: 'won',
    date: new Date('2024-05-12T02:00:00.000Z').toISOString(),
  }
];

export const SPORTS: Sport[] = ['Football', 'Basketball', 'Tennis', 'Baseball', 'Other'];
